# Generated by Django 4.2.2 on 2023-06-20 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_rename_usuario_task_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='fecha_completada',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
